export const isStorePageVisitedId: string = 'is_store_page_visited';
export const ourCodesToSubgroup: IOurCodesToSubgroup = {
  jacket: {
    bak: 'back',
    buo: 'buttons',
    cpk: 'chest_pocket',
    mdl: 'model',
    pks: 'pockets',
    sle: 'sleeves',
  },
  pants: {
    mds: 'model',
  },
  shirt: {
    bck: 'back',
    btc: 'buttonholes_color',
    btn: 'buttons',
    clr: 'collar',
    cfs: 'cuffs',
    frt: 'front',
    hem: 'hem',
    irt: 'initials_arrangement',
    inc: 'initials_color',
    ist: 'initials_style',
    slv: 'sleeves',
    yke: 'yoke',
  },
};

export const dummyAssetsId: IDummyAssetsId = {
  bak: 'jacket',
  buo: 'jacket',
  cpk: 'jacket',
  mdl: 'jacket',
  pks: 'jacket',
  sle: 'jacket',
  mds: 'pants',
  bck: 'shirt',
  btc: 'shirt',
  btn: 'shirt',
  clr: 'shirt',
  cfs: 'shirt',
  frt: 'shirt',
  hem: 'shirt',
  irt: 'shirt',
  inc: 'shirt',
  ist: 'shirt',
  slv: 'shirt',
  yke: 'shirt',
};
